// Generated by https://quicktype.io

import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:transport/model/driverModel.dart';

class StudentModel {
  String? regNo;
  String? name;
  String? phone;
  String? role;
  String? routeNo;
  String? routeName;
  String? busId;
  List<StopsModel>? stops;
  // LatLng? driverLocation;

  StudentModel({
    this.regNo,
    this.name,
    this.phone,
    this.role,
    this.routeNo,
    this.routeName,
    this.stops,
    this.busId,
  });
  factory StudentModel.fromjson(Map<String, dynamic> value) {
    return StudentModel(
      busId: value['bus_id'].toString(),
      name: value['Name'] ?? '',
      regNo: value['reg_no'] ?? '',
      phone: value['Phone'].toString(),
      role: value['role'] ?? '',
      routeName: value['route_name'] ?? '',
      routeNo: value['route_no'].toString(),
      stops: <StopsModel>[...value['stops'].map((e) => StopsModel.fromJson(e))],
    );
  }
  factory StudentModel.empty() {
    return StudentModel(
      busId: '',
      name: '',
      regNo: '',
      phone: '',
      role: '',
      routeName: '',
      routeNo: '',
      stops: []
      // driverLocation: LatLng(0, 0)
    );
  }
}
